import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers/Providers";
import { Toaster } from "react-hot-toast";
import PrivateRoute from "@/components/Shared/PrivateRoute/PrivateRoute";
import AgeVerification from "@/components/Shared/AgeVerification";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OCS (Buy Now)",
  description: "Generated by create OCS (Buy Now)",
  icons: {
    icon: "/favicon.png", // <-- global favicon
    apple: "/favicon.png", // optional for Apple devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AgeVerification />
          <PrivateRoute>{children}</PrivateRoute>
          <Toaster position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
